name = "cargo"
description = "Cargo package manager hooks"
entry_point = "main.ts"

[permissions]
write = ["./", "~/.cargo", "~/.local/share/phylum/extensions/cargo"]
read = true
run = true
net = true
unsandboxed_run = ["cargo"]
