---

name: Sync `docs` directory to ReadMe

on:
  workflow_dispatch:
  push:
    branches:
      - master
  
jobs:
  Update-Documentation:
    name: Update the documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
       
      - name: Update v1-latest using rdme
        uses: readmeio/rdme@7.0.0
        with:
          rdme: docs ./docs --key=${{ secrets.README_API }} --version=1-latest
